### ISSUE TITLE
Less than symbol not rendered correctly

### ISSUE THREAD

**Issue by mmicu** [lzanini/mdbook-katex#114]
The `<` symbol is not rendered correctly. This is an example:

```markdown
hello

$$ a < 1 $$

world

$$ a > 1 $$
```

<img width="422" alt="image" src="https://github.com/lzanini/mdbook-katex/assets/14826658/525075a1-cac3-4d71-ad88-738a9b85a9ec">

That's what I am using:

```
mdbook v0.4.37:
    mdbook
mdbook-graphviz v0.2.0:
    mdbook-graphviz
mdbook-katex v0.8.1:
    mdbook-katex
```

With the following `TOML` configuration:

```toml
[output.html]
additional-css = ["src/css/cookieconsent.css"]
mathjax-support = true

[preprocessor.katex]
after = ["links"]
throw-on-error = true

[preprocessor.graphviz]
command = "mdbook-graphviz"
output-to-file = false
after = ["links"]

[output.html.code.hidelines]
python = "~"
```

**Comment by SichangHe** [comment]
Unfortunately, I cannot reproduce this. Could you

1. tell me how you installed mdBook-KaTeX (especially if you are on Windows), and
1. remove the `[output.html]` entry from your `book.toml` and try again?

**Comment by mmicu** [comment]
I have solved it by using the following configuration. It is the same that I wrote above by only changing the `after` parameter for `preprocessor.katex`:

```toml
[output.html]
additional-css = ["src/css/cookieconsent.css"]
mathjax-support = true

[preprocessor.katex]
after = ["preprocessor.graphviz"]
throw-on-error = true

[preprocessor.graphviz]
command = "mdbook-graphviz"
output-to-file = false
after = ["links"]

[output.html.code.hidelines]
python = "~"
```
