### ISSUE TITLE
Offscreen Tex content

### ISSUE THREAD

**Issue by Azgrom** [lzanini/mdbook-katex#4]
Hi! I noticed the inconvenience of a large line of **_Tex_** content continuing after the mdbook page width ends.

Here is a image showing it:
![offscreen1](https://user-images.githubusercontent.com/14893177/106938266-8475be00-66fd-11eb-840e-ab3d1f13455d.png)

With the laptop's touchpad I can scroll right to se the remaining content, such as in the following image:
![offscreen2](https://user-images.githubusercontent.com/14893177/106938443-c43ca580-66fd-11eb-971e-78ae4d064640.png)
On this second image one can notice the entire content is moved to the left. There is no of that margin defined by mdbook...

I am not sure if it is a mdbook-katex thing. Is there some hidden margin configuration I am not aware?
Here is the feedback, Just in case.

**Comment by lzanini** [comment]
Hello, 

I've had this issue before with figures / large tables without equations, so I think it has to do with the way mdbook defines its margins rather than with this preprocessor.

Anyway, you can probably get away with some css code, for example

```css
/* additional.css */
.content main {
    margin-left: 1%;
    margin-right: 1%;
}
```

and adding to your toml file

```toml
[output.html]
additional-css = ["path/to/additional.css"]
```

If you have some CSS knowledge (I don't) you can probably do something better than this, and adjust the margins dynamically depending on the content size. If you manage to do that, let me know !
