### ISSUE TITLE
`mdbook serve` doesn't work

### ISSUE THREAD

**Issue by stO-Orz** [lzanini/mdbook-katex#43]
After I run the command `cargo install mdbook-katex` and modify the `.toml` file. The command `mdbook serve` doesn't work.

The info was

```txt
2022-12-09 10:26:56 [INFO] (mdbook::book): Book building has started
Error: The katex preprocessor/renderer did not understand what you wantedto do
2022-12-09 10:26:56 [ERROR] (mdbook::utils): Error: The "katex" preprocessor exited unsuccessfully with exit code: 1 status
```

All the above work was done on a  Mac environment.

P.S. An extra question, is that ok for me just leave the options be emty and just put the following lines in the `.toml` file? It not, what should write under them? I can't find some documents to discuss this problem in detail.

```txt
[output.katex]

[preprocessor.katex]
```

**Comment by SichangHe** [comment]
For you reference, [here](https://github.com/SichangHe/notes/blob/bc52123762843b67e1d8589807b038dea27d92b7/book.toml) is an example `book.toml`:
```toml
[book]
authors = ["Steven Hé (Sīchàng)"]
language = "en"
multilingual = false
src = "src"
title = "Steven's Notes"

[build]
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/SichangHe/notes"

[output.katex]

[preprocessor.katex]
```

Does this solve your problem? If not, could you post your minimum `book.toml` file?

**Comment by stO-Orz** [comment]
Thanks for your help. But it still doesn't work. Here's my `book.toml` file.

```toml
[book]
authors = ["Orz"]
language = "en"
multilingual = false
src = "src"
title = "Notes"

[output.html]
additional-css = ["custom/custom.css"]
no-section-label = true

[output.html.fold]
enable = true
level = 0

[output.katex]

[preprocessor.katex]
```
