### ISSUE TITLE
matrix rendering

### ISSUE THREAD

**Issue by justletmecreatetheaccount** [lzanini/mdbook-katex#98]
hello ! 

mdbook-katex don't render my matrices but they're syntax good since https://katex.org/#demo is showing me the matrix without error

here is an example of the "buggy" code:

`$$\begin{bmatrix}P & Q \\\frac{\text{d}x}{\text{d}s} & \frac{\text{d}y}{\text{d}s} \\ \end{bmatrix}\begin{bmatrix} \frac{\partial u}{\partial x} \\ \frac{\partial u}{\partial y} \\ \end{bmatrix}= \begin{bmatrix} R \\ \frac{\text{d}u}{\text{d}s} \\ \end{bmatrix}$$`

mdbook-katex process it well because dollars signs gets removed when katex enabled, but it does not show me my matrix, but only the latex text

![image](https://github.com/lzanini/mdbook-katex/assets/112435002/6e441fd2-7f5b-4963-99f1-17256eda4ac8)

Is the problem coming from me ?

Here is my book.toml
```toml

[book]
authors = ["[Vlad Doniga]"]
language = "fr"
multilingual = false
src = "src"
title = "LEPL1103 - Notes"

[preprocessor.katex]
after = ["links"]
throw-on-error = false

[output.html]
# theme = "my-theme"
default-theme = "light"
preferred-dark-theme = "ayu"
# curly-quotes = true
# mathjax-support = false
# copy-fonts = true
# additional-css = ["custom.css", "custom2.css"]
# additional-js = ["custom.js"]
# no-section-label = false
git-repository-url = "https://github.com/MoinesCopistes/lepl1103"
git-repository-icon = "fa-github"
additional-css = ['mdbook-admonish.css','katex-supp.css']
# edit-url-template = "https://github.com/rust-lang/mdBook/edit/master/guide/{path}"
# site-url = "/example-book/"
# cname = "myproject.rs"
# input-404 = "not-found.md"
```

But anyway, thank you for building this tool, it's like **REALLY** helpful !
